### ISSUE TITLE
Contract deployment frontend

### ISSUE THREAD

**Issue by FalkoKa** [bangtam1994/Re-sell-dapp#19]
We want to deploy a contract in the frontend after a form submit.

Should we use the viem "deployContract" function ([deployContract](https://viem.sh/docs/contract/deployContract.html))
- downside: need the contract bytecode in hex

Or deploy it like we did in the class with ethers and typechain types Contract Factories 
- downside: would need to add all these dependencies to the scaffold eth frontend

**Comment by MatheusDaros** [comment]
Thanks for opening this issue @FalkoKa 

> would need to add all these dependencies to the scaffold eth frontend

This is quite problematic to do nowadays. For SE, I'd suggest sticking with `viem` methods like `deployContract` and fetching the needed data with the json file like we did in week 4.

**Comment by deca12x** [comment]
@MatheusDaros We are still struggling - viem's function deployContract is only returning the transaction hash - We're not sure how to get the contract address at deployment

**Comment by MatheusDaros** [comment]
Hello @deca12x 
The same way that in `Ethers` we need to wait for the contract to be deployed, in `Viem` you need to wait for the deploy transaction to be completed. The network behavior is the same independent of the library you're using to interface with it.

There's a [simple example](https://stackblitz.com/github/wevm/viem/tree/main/examples/contracts_deploying-contracts?file=index.tsx) at the docs that's worth checking.

Also, whenever you want to pick any contract deployed in a transaction, you can also use the [getContractAddress](https://viem.sh/docs/utilities/getContractAddress.html) method by passing the address of the deployer and the nonce of the transaction.
