### ISSUE TITLE
Set up Mongo DB

### ISSUE THREAD

**Issue by FabianRadomski** [bangtam1994/Re-sell-dapp#3]
We need a database for our backend

**Comment by askh01** [comment]
yes we know this, thanks a lot for creating a mongodb atlas instance :)

**Comment by FabianRadomski** [comment]
> yes we know this, thanks a lot for creating a mongodb atlas instance :)

Hahah, just was showing @deca12x what I mean with Github issues for tasks, I will continue to add all other tasks today

**Comment by deca12x** [comment]
👍
